🌧 Karnataka Flood Risk Intelligence System (KFRIS)

🎯 Project Objectives 
🔹 Analyze District-wise Rainfall Data
    Understand the annual rainfall distribution across Karnataka districts.
🔹 Perform Data Cleaning Using Pandas
    Handle missing values, convert data types, and prepare dataset for analysis.
🔹Apply Filtering and Conditional Logic
   Classify districts based on rainfall thresholds using Pandas operations.

🔹 Identify High-Risk and Safest Districts
    Detect top dangerous districts (high rainfall) and safest districts (low rainfall).
🔹 Practice Core Pandas Operations
Use `.read_csv()`, `.head()`, `.sort_values()`, filtering, and conditional selection.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Rainfall_2016_districtwise.csv')
df.head()

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
0,2,BENGALURU(R),19,4,23,45,751
1,3,RAMANAGARA,24,3,27,43,822
2,4,CHITRADURGA,33,5,38,40,507
3,5,DAVANAGERE,36,5,41,56,637
4,6,KOLAR,30,5,35,35,622

df.head() -displays the first 5 rows of the dataset

In [3]:
df.head(2)

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
0,2,BENGALURU(R),19,4,23,45,751
1,3,RAMANAGARA,24,3,27,43,822

df.head(2)-it will display the top 2 rows of the dataset,we can modify the numbers within ()

df.tail()

df.tail() will display the last 5 rows of the dataset

In [4]:
df.tail(2)

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
28,30,KOPPAL,30,1,31,37,587
29,STATE,Total,1136,138,1274,61,1220

df.tail(2) will display the last 2 rows of the dataset respectively.Modification of number done inside the ()

In [5]:
df.shape

(30, 7)

df.shape will display the number of rows and columns

for ex:(rows,columns)=(30,7)

In [6]:
print("Number of rows: ",df.shape[0])
print("Number of columns: ",df.shape[1])

Number of rows:  30
Number of columns:  7

df.shape[0]-0 represents rows
df.shape[1]-1 represents columns and together they display it in with help of print statement

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Sl.No                             30 non-null     object
 1   Districts                         30 non-null     object
 2   RaingaugeStations_Working  R,Gs   30 non-null     int64
 3   RaingaugeStations_Not Working     30 non-null     int64
 4   Raingauge Stations_Total          30 non-null     int64
 5   Annual Normal Rainfall_Rainydays  30 non-null     int64
 6   Normal Rainfall                   30 non-null     int64
dtypes: int64(5), object(2)
memory usage: 1.8+ KB

it displays the information about the dataset with respect to number of columns,Dtypes and Non-null Count

In [8]:
df.isnull()

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False

df.isnull() is used to check null values in datasets respectively

In [9]:
df.isnull().sum()

Sl.No                               0
Districts                           0
RaingaugeStations_Working  R,Gs     0
RaingaugeStations_Not Working       0
Raingauge Stations_Total            0
Annual Normal Rainfall_Rainydays    0
Normal Rainfall                     0
dtype: int64

df.isnull().sum() will display null value count

In [10]:
df.isnull().sum(axis=1)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
dtype: int64

df.isnull().sum(axis=1) here if we declare axis=1 it will display value in row wise,if axis=0,it will display values in columnwise

In [11]:
df.describe()

,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
count,30.000000,30.000000,30.000000,30.000000,30.000000
mean,75.733333,9.200000,84.933333,60.700000,1197.400000
std,201.222631,24.498276,225.508152,29.019791,994.538417
min,15.000000,0.000000,18.000000,34.000000,507.000000
25%,28.500000,3.000000,31.000000,36.250000,633.250000
50%,33.000000,4.500000,39.500000,52.000000,766.500000
75%,43.750000,7.000000,49.750000,74.750000,1081.750000
max,1136.000000,138.000000,1274.000000,129.000000,4285.000000

df.describe() will display the statistics of number columns as shown above

In [12]:
df.describe(include='all')

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
count,30,30,30.000000,30.000000,30.000000,30.000000,30.000000
unique,30,30,NaN,NaN,NaN,NaN,NaN
top,2,BENGALURU(R),NaN,NaN,NaN,NaN,NaN
freq,1,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,75.733333,9.200000,84.933333,60.700000,1197.400000
std,NaN,NaN,201.222631,24.498276,225.508152,29.019791,994.538417
min,NaN,NaN,15.000000,0.000000,18.000000,34.000000,507.000000
25%,NaN,NaN,28.500000,3.000000,31.000000,36.250000,633.250000
50%,NaN,NaN,33.000000,4.500000,39.500000,52.000000,766.500000
75%,NaN,NaN,43.750000,7.000000,49.750000,74.750000,1081.750000
max,NaN,NaN,1136.000000,138.000000,1274.000000,129.000000,4285.000000

df.describe(include='all') will display the statistics of all the columns respectively

In [13]:
df.columns = df.columns.str.strip()

In [14]:
print(df.columns)

Index(['Sl.No', 'Districts', 'RaingaugeStations_Working  R,Gs',
       'RaingaugeStations_Not Working', 'Raingauge Stations_Total',
       'Annual Normal Rainfall_Rainydays', 'Normal Rainfall'],
      dtype='object')

In [15]:
df['Districts'].unique()

array(['BENGALURU(R)', 'RAMANAGARA', 'CHITRADURGA', 'DAVANAGERE', 'KOLAR',
       'CHIKKABALLAPURA', 'SHIVAMOGGA', 'TUMAKURU', 'CHIKKAMAGALURU',
       'DAKSHINA KANNADA', 'UDUPI', 'HASSAN', 'KODAGU', 'MANDYA',
       'MYSURU', 'CHAMARAJANAGAR', 'BELAGAVI', 'VIJAYAPURA', 'BAGALKOT',
       'DHARAWAD', 'GADAG', 'HAVERI', 'UTTARA KANNADA', 'BALLARI',
       'BIDAR', 'KALABURAGI', 'YADGIRI', 'RAICHUR', 'KOPPAL', 'Total'],
      dtype=object)

Before performing analysis, basic data cleaning was applied:

 Removed extra spaces from column names using `.str.strip()`
 Verified correct column names using `df.columns`
 Checked dataset structure using `df.head()` and `df.shape`
 Ensured correct data formatting for further analysis

This step ensures accurate filtering, sorting, and rainfall classification.

df['Districts'].unique() will display the name of districts in above format

In [16]:
df['Districts'].value_counts()

Districts
BENGALURU(R)        1
RAMANAGARA          1
KOPPAL              1
RAICHUR             1
YADGIRI             1
KALABURAGI          1
BIDAR               1
BALLARI             1
UTTARA KANNADA      1
HAVERI              1
GADAG               1
DHARAWAD            1
BAGALKOT            1
VIJAYAPURA          1
BELAGAVI            1
CHAMARAJANAGAR      1
MYSURU              1
MANDYA              1
KODAGU              1
HASSAN              1
UDUPI               1
DAKSHINA KANNADA    1
CHIKKAMAGALURU      1
TUMAKURU            1
SHIVAMOGGA          1
CHIKKABALLAPURA     1
KOLAR               1
DAVANAGERE          1
CHITRADURGA         1
Total               1
Name: count, dtype: int64

value_counts() function in pandas help to display the unique values

In [17]:
print("District with Low annual rainfall")
df[df['Normal Rainfall']<=700]

District with Low annual rainfall

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
2,4,CHITRADURGA,33,5,38,40,507
3,5,DAVANAGERE,36,5,41,56,637
4,6,KOLAR,30,5,35,35,622
5,7,CHIKKABALLAPURA,31,4,35,92,677
7,9,TUMAKURU,66,2,68,36,589
13,15,MANDYA,32,0,32,36,655
17,19,VIJAYAPURA,33,6,39,39,632
18,20,BAGALKOT,28,3,31,36,588
20,22,GADAG,15,3,18,35,631
23,25,BALLARI,38,7,45,34,606
27,29,RAICHUR,40,7,47,36,658
28,30,KOPPAL,30,1,31,37,587

this particular method will classify districts based on lowest rainfall value respectively and display the other details of other columns

In [18]:
df[(df['Normal Rainfall']>=700) & (df['Normal Rainfall']<=1200)]

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
0,2,BENGALURU(R),19,4,23,45,751
1,3,RAMANAGARA,24,3,27,43,822
11,13,HASSAN,59,1,60,78,1147
14,16,MYSURU,40,9,49,53,739
15,17,CHAMARAJANAGAR,27,4,31,36,735
16,18,BELAGAVI,90,7,97,52,844
19,21,DHARAWAD,19,6,25,60,787
21,23,HAVERI,33,4,37,65,782
24,26,BIDAR,36,4,40,57,886
25,27,KALABURAGI,45,7,52,52,842
26,28,YADGIRI,20,0,20,48,832

this particular method will display the value of districts along with other values bases on classification

In [19]:
df['Normal Rainfall'].between(700,1200)

0      True
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14     True
15     True
16     True
17    False
18    False
19     True
20    False
21     True
22    False
23    False
24     True
25     True
26     True
27    False
28    False
29    False
Name: Normal Rainfall, dtype: bool

df[column name].between(val1,val2) will works as alternative method

In [18]:
df

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
0,2,BENGALURU(R),19,4,23,45,751
1,3,RAMANAGARA,24,3,27,43,822
2,4,CHITRADURGA,33,5,38,40,507
3,5,DAVANAGERE,36,5,41,56,637
4,6,KOLAR,30,5,35,35,622
5,7,CHIKKABALLAPURA,31,4,35,92,677
6,8,SHIVAMOGGA,88,5,93,99,2682
7,9,TUMAKURU,66,2,68,36,589
8,10,CHIKKAMAGALURU,46,4,50,92,2075
9,11,DAKSHINA KANNADA,33,10,43,127,3524
10,12,UDUPI,26,2,28,129,4285
11,13,HASSAN,59,1,60,78,1147
12,14,KODAGU,33,13,46,106,2693
13,15,MANDYA,32,0,32,36,655
14,16,MYSURU,40,9,49,53,739
15,17,CHAMARAJANAGAR,27,4,31,36,735
16,18,BELAGAVI,90,7,97,52,844
17,19,VIJAYAPURA,33,6,39,39,632
18,20,BAGALKOT,28,3,31,36,588
19,21,DHARAWAD,19,6,25,60,787
20,22,GADAG,15,3,18,35,631
21,23,HAVERI,33,4,37,65,782
22,24,UTTARA KANNADA,86,7,93,106,2887
23,25,BALLARI,38,7,45,34,606
24,26,BIDAR,36,4,40,57,886
25,27,KALABURAGI,45,7,52,52,842
26,28,YADGIRI,20,0,20,48,832
27,29,RAICHUR,40,7,47,36,658
28,30,KOPPAL,30,1,31,37,587
29,STATE,Total,1136,138,1274,61,1220

In [20]:
df['Normal Rainfall'].mean()

1197.4

mean() method will display the average value of Normal rainfall column

In [21]:
df['Normal Rainfall'].min()

507

min() method will display the min value from the Normal Rainfall column

In [22]:
df['Normal Rainfall'].max()

4285

max() methond will display the max value from the Normal Rainfall column

In [24]:
#APPLY METHOD
def rainfall(x):
    return x/2

In [25]:
df['Normal Rainfall'].apply(rainfall)

0      375.5
1      411.0
2      253.5
3      318.5
4      311.0
5      338.5
6     1341.0
7      294.5
8     1037.5
9     1762.0
10    2142.5
11     573.5
12    1346.5
13     327.5
14     369.5
15     367.5
16     422.0
17     316.0
18     294.0
19     393.5
20     315.5
21     391.0
22    1443.5
23     303.0
24     443.0
25     421.0
26     416.0
27     329.0
28     293.5
29     610.0
Name: Normal Rainfall, dtype: float64

In apply method first we have to create function named rainfall then we have to return x/2 and in second column we have to use apply method and rainfall inside() and it will return half values of rainfall column

In [29]:
df['Districts'].apply(len)

0     12
1     10
2     11
3     10
4      5
5     15
6     10
7      8
8     14
9     16
10     5
11     6
12     6
13     6
14     6
15    14
16     8
17    10
18     8
19     8
20     5
21     6
22    14
23     7
24     5
25    10
26     7
27     7
28     6
29     5
Name: Districts, dtype: int64

In [32]:
#DROP THE COLUMNS
df

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall,partial_rainfall
0,2,BENGALURU(R),19,4,23,45,751,375.5
1,3,RAMANAGARA,24,3,27,43,822,411.0
2,4,CHITRADURGA,33,5,38,40,507,253.5
3,5,DAVANAGERE,36,5,41,56,637,318.5
4,6,KOLAR,30,5,35,35,622,311.0
5,7,CHIKKABALLAPURA,31,4,35,92,677,338.5
6,8,SHIVAMOGGA,88,5,93,99,2682,1341.0
7,9,TUMAKURU,66,2,68,36,589,294.5
8,10,CHIKKAMAGALURU,46,4,50,92,2075,1037.5
9,11,DAKSHINA KANNADA,33,10,43,127,3524,1762.0
10,12,UDUPI,26,2,28,129,4285,2142.5
11,13,HASSAN,59,1,60,78,1147,573.5
12,14,KODAGU,33,13,46,106,2693,1346.5
13,15,MANDYA,32,0,32,36,655,327.5
14,16,MYSURU,40,9,49,53,739,369.5
15,17,CHAMARAJANAGAR,27,4,31,36,735,367.5
16,18,BELAGAVI,90,7,97,52,844,422.0
17,19,VIJAYAPURA,33,6,39,39,632,316.0
18,20,BAGALKOT,28,3,31,36,588,294.0
19,21,DHARAWAD,19,6,25,60,787,393.5
20,22,GADAG,15,3,18,35,631,315.5
21,23,HAVERI,33,4,37,65,782,391.0
22,24,UTTARA KANNADA,86,7,93,106,2887,1443.5
23,25,BALLARI,38,7,45,34,606,303.0
24,26,BIDAR,36,4,40,57,886,443.0
25,27,KALABURAGI,45,7,52,52,842,421.0
26,28,YADGIRI,20,0,20,48,832,416.0
27,29,RAICHUR,40,7,47,36,658,329.0
28,30,KOPPAL,30,1,31,37,587,293.5
29,STATE,Total,1136,138,1274,61,1220,610.0

In [34]:
df.drop('partial_rainfall',axis=1)

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall
0,2,BENGALURU(R),19,4,23,45,751
1,3,RAMANAGARA,24,3,27,43,822
2,4,CHITRADURGA,33,5,38,40,507
3,5,DAVANAGERE,36,5,41,56,637
4,6,KOLAR,30,5,35,35,622
5,7,CHIKKABALLAPURA,31,4,35,92,677
6,8,SHIVAMOGGA,88,5,93,99,2682
7,9,TUMAKURU,66,2,68,36,589
8,10,CHIKKAMAGALURU,46,4,50,92,2075
9,11,DAKSHINA KANNADA,33,10,43,127,3524
10,12,UDUPI,26,2,28,129,4285
11,13,HASSAN,59,1,60,78,1147
12,14,KODAGU,33,13,46,106,2693
13,15,MANDYA,32,0,32,36,655
14,16,MYSURU,40,9,49,53,739
15,17,CHAMARAJANAGAR,27,4,31,36,735
16,18,BELAGAVI,90,7,97,52,844
17,19,VIJAYAPURA,33,6,39,39,632
18,20,BAGALKOT,28,3,31,36,588
19,21,DHARAWAD,19,6,25,60,787
20,22,GADAG,15,3,18,35,631
21,23,HAVERI,33,4,37,65,782
22,24,UTTARA KANNADA,86,7,93,106,2887
23,25,BALLARI,38,7,45,34,606
24,26,BIDAR,36,4,40,57,886
25,27,KALABURAGI,45,7,52,52,842
26,28,YADGIRI,20,0,20,48,832
27,29,RAICHUR,40,7,47,36,658
28,30,KOPPAL,30,1,31,37,587
29,STATE,Total,1136,138,1274,61,1220

df['partial_rainfall']=df['Normal Rainfall'].apply(rainfall) will create a new column named partial_rainfall and when I used drop method,automatically partial_rainfall method gets dropped

In [35]:
df.columns

Index(['Sl.No', 'Districts', 'RaingaugeStations_Working  R,Gs',
       'RaingaugeStations_Not Working', 'Raingauge Stations_Total',
       'Annual Normal Rainfall_Rainydays', 'Normal Rainfall',
       'partial_rainfall'],
      dtype='object')

df.columns prints the name of the columns

In [36]:
df.index

RangeIndex(start=0, stop=30, step=1)

df.index will display the index values

In [37]:
df.sort_values(by='RaingaugeStations_Not Working')

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall,partial_rainfall
26,28,YADGIRI,20,0,20,48,832,416.0
13,15,MANDYA,32,0,32,36,655,327.5
28,30,KOPPAL,30,1,31,37,587,293.5
11,13,HASSAN,59,1,60,78,1147,573.5
7,9,TUMAKURU,66,2,68,36,589,294.5
10,12,UDUPI,26,2,28,129,4285,2142.5
1,3,RAMANAGARA,24,3,27,43,822,411.0
20,22,GADAG,15,3,18,35,631,315.5
18,20,BAGALKOT,28,3,31,36,588,294.0
21,23,HAVERI,33,4,37,65,782,391.0
15,17,CHAMARAJANAGAR,27,4,31,36,735,367.5
24,26,BIDAR,36,4,40,57,886,443.0
0,2,BENGALURU(R),19,4,23,45,751,375.5
8,10,CHIKKAMAGALURU,46,4,50,92,2075,1037.5
5,7,CHIKKABALLAPURA,31,4,35,92,677,338.5
6,8,SHIVAMOGGA,88,5,93,99,2682,1341.0
4,6,KOLAR,30,5,35,35,622,311.0
3,5,DAVANAGERE,36,5,41,56,637,318.5
2,4,CHITRADURGA,33,5,38,40,507,253.5
17,19,VIJAYAPURA,33,6,39,39,632,316.0
19,21,DHARAWAD,19,6,25,60,787,393.5
16,18,BELAGAVI,90,7,97,52,844,422.0
22,24,UTTARA KANNADA,86,7,93,106,2887,1443.5
23,25,BALLARI,38,7,45,34,606,303.0
27,29,RAICHUR,40,7,47,36,658,329.0
25,27,KALABURAGI,45,7,52,52,842,421.0
14,16,MYSURU,40,9,49,53,739,369.5
9,11,DAKSHINA KANNADA,33,10,43,127,3524,1762.0
12,14,KODAGU,33,13,46,106,2693,1346.5
29,STATE,Total,1136,138,1274,61,1220,610.0

by using sort() method,RaingaugeStations_Not Working values will get sorted in ascending order as a results all the other columns gets sorted according to this particular column(RaingaugeStations_Not Working)

In [38]:
df.sort_values(by='RaingaugeStations_Not Working',ascending=False)

,Sl.No,Districts,"RaingaugeStations_Working R,Gs",RaingaugeStations_Not Working,Raingauge Stations_Total,Annual Normal Rainfall_Rainydays,Normal Rainfall,partial_rainfall
29,STATE,Total,1136,138,1274,61,1220,610.0
12,14,KODAGU,33,13,46,106,2693,1346.5
9,11,DAKSHINA KANNADA,33,10,43,127,3524,1762.0
14,16,MYSURU,40,9,49,53,739,369.5
25,27,KALABURAGI,45,7,52,52,842,421.0
22,24,UTTARA KANNADA,86,7,93,106,2887,1443.5
23,25,BALLARI,38,7,45,34,606,303.0
16,18,BELAGAVI,90,7,97,52,844,422.0
27,29,RAICHUR,40,7,47,36,658,329.0
17,19,VIJAYAPURA,33,6,39,39,632,316.0
19,21,DHARAWAD,19,6,25,60,787,393.5
6,8,SHIVAMOGGA,88,5,93,99,2682,1341.0
4,6,KOLAR,30,5,35,35,622,311.0
3,5,DAVANAGERE,36,5,41,56,637,318.5
2,4,CHITRADURGA,33,5,38,40,507,253.5
21,23,HAVERI,33,4,37,65,782,391.0
24,26,BIDAR,36,4,40,57,886,443.0
0,2,BENGALURU(R),19,4,23,45,751,375.5
8,10,CHIKKAMAGALURU,46,4,50,92,2075,1037.5
5,7,CHIKKABALLAPURA,31,4,35,92,677,338.5
15,17,CHAMARAJANAGAR,27,4,31,36,735,367.5
18,20,BAGALKOT,28,3,31,36,588,294.0
1,3,RAMANAGARA,24,3,27,43,822,411.0
20,22,GADAG,15,3,18,35,631,315.5
10,12,UDUPI,26,2,28,129,4285,2142.5
7,9,TUMAKURU,66,2,68,36,589,294.5
11,13,HASSAN,59,1,60,78,1147,573.5
28,30,KOPPAL,30,1,31,37,587,293.5
13,15,MANDYA,32,0,32,36,655,327.5
26,28,YADGIRI,20,0,20,48,832,416.0

when we add ascending=False values gets sorted in descending order